// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsfk5L-dEblmatR7EkVrGO_pFZijMO8HU',
    appId: '1:441482129781:web:feaedc4554ce944ddb633c',
    messagingSenderId: '441482129781',
    projectId: 'kobuk-dd149',
    authDomain: 'kobuk-dd149.firebaseapp.com',
    storageBucket: 'kobuk-dd149.appspot.com',
    measurementId: 'G-HTFLNX1KCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaF4ex5j48p1HLH5vRMRpSmo6LO6SVr74',
    appId: '1:441482129781:android:3d19837828064380db633c',
    messagingSenderId: '441482129781',
    projectId: 'kobuk-dd149',
    storageBucket: 'kobuk-dd149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAAFNU1zNXVgRvvGvxYVjkhDGRTETKuo0',
    appId: '1:441482129781:ios:830f087416ab8019db633c',
    messagingSenderId: '441482129781',
    projectId: 'kobuk-dd149',
    storageBucket: 'kobuk-dd149.appspot.com',
    iosBundleId: 'com.example.kobuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAAFNU1zNXVgRvvGvxYVjkhDGRTETKuo0',
    appId: '1:441482129781:ios:85878c493fb98fbcdb633c',
    messagingSenderId: '441482129781',
    projectId: 'kobuk-dd149',
    storageBucket: 'kobuk-dd149.appspot.com',
    iosBundleId: 'com.example.kobuk.RunnerTests',
  );
}
